### ISSUE TITLE
Document how to use the admin interface in Directus

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/onrr.gov-site#2053]

**Comment by mcharg** [comment]
See #2052 for one example to document.

**Comment by cthomasONRR** [comment]
This can be closed since I did add some documentation here: https://github.com/ONRR/onrr.gov-site/wiki/CMS-admin-guide. This was meant for us to get detailed documentation from a pervious developer who was not communicating with us. Now that Jeff is providing amazing documentation, we can just continue to add to this wiki page as needed.
