### ISSUE TITLE
Review business cards for conference

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#2593]
Hi all, 

Please review 3 things and let me know if I should make any edits:
- your personal business card
- the general (ODDD team) business card
- the sicker

All can be found in this folder: https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Outreach/BusinessCards/Individual-Business-Cards/PDF?csf=1&web=1&e=uXvrJn

**Comment by cthomasONRR** [comment]
@AlexandracmONRR These look great! This is super nit-picky, but I think our team name needs an Oxford comma. "Open Data, Design, and Development" instead of "Open Data, Design and Development". This is for all instances of our team name.

**Comment by Maroyafaied** [comment]
@AlexandracmONRR My card is beautiful, I love it. For the general card, I wonder how it would look if you took out "(ODDD)Team" and my phone number and moved the mailbox address and the github url to the left side and on the right side listed the 3 sites instead of them being on the back.  I love the sticker, I don't have any changes on that. 
![image](https://user-images.githubusercontent.com/40175688/231579238-648b359b-cb90-41de-9d1e-93b4a9f5ce76.png)

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - What do you think about this mock-up?

![image](https://user-images.githubusercontent.com/122935097/231582566-3114a4c6-012a-4462-ad02-a831531c6f99.png)

I think the back of the card looks a little empty without the website URLs under the title, but it's also maybe repetitive. What do you think?

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - what do you think about this?
![image](https://user-images.githubusercontent.com/122935097/231584291-b836569c-51c6-4da6-b3c5-781d2b9e19fd.png)

Do you think it is an issue if we don't have the titles of ODDD, ONRR, and NRRD though?

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I like it, I don't think it's an issue since the urls are pretty descriptive, I'm happy to hear what you think as well as @cthomasONRR and @lpgoldstein .  The agency name is missing though, so maybe we can add that above the buffalos or on the left side.  Another annoying request if it's possible, can we add a mail icon before the email address and the GitHub icon before the github url?

**Comment by AlexandracmONRR** [comment]
@Maroyafaied @lpgoldstein @cthomasONRR - thanks for all your comment. I've added the team name on the left side. Anything else that we need to change about this team card?
![image.png](https://images.zenhubusercontent.com/63c714c1834273d5ce0f96fb/786716d6-c650-4d69-a620-2442e21dd920)

**Comment by cthomasONRR** [comment]
@AlexandracmONRR Looks great!

**Comment by lpgoldstein** [comment]
@AlexandracmONRR Love it!

**Comment by AlexandracmONRR** [comment]
Awesome - thank you all!

I've exported all of the edited business cards here: https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Outreach/BusinessCards/Individual-Business-Cards/PDF?csf=1&web=1&e=uXvrJn

I'm going to close this issue!
