### ISSUE TITLE
Follow up on ANDI

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2642]

**Comment by eelzi-ONRR** [comment]
From Sid: 

Is the issue you are experiencing same as Content Security Policy blocking?  Determine if ANDI is being blocked by CSP:

Navigate to test page
Open dev tools and go to console
Launch ANDI
If you see an error appear in console that talks about Content Security Policy, then, to continue using ANDI to test this page, you will need to install a browser extension that turns off Content Security Policy for Edge:

Open Microsoft Edge and go to the Chrome Web Store.
Press the button to "Allow extensions from other stores"
Find the Disable Content-Security-Policy extension from the Chrome Web Store
Select the Disable Content-Security-Policy extension button in the Chrome browser toolbar to disable CSP
Navigate to the test page, launch ANDI
 
When done testing with ANDI, re-enable CSP
 






[6:29 AM] Sharma, Siddhartha




If that doesn't solve the issue, since all bookmarks scripts are being blocked by a browser setting, then you may have to use a diff browser or execute the ANDI script from the dev tools console.







[6:32 AM] Sharma, Siddhartha




If the above does not solve the issue you are experiencing, please send an email to John Cotterr at SSA and copy me. John was involved in the development of ANDI and may be able to assist. His email address is Cotter, John <John.Cotter@ssa.gov>

**Comment by Maroyafaied** [comment]
The org settings has javascript blocked and it prevents the ANDI bookmark from working. The workaround is copying and pasting the javascript url to the dev console. Another way is adding a snippet in dev tools using the instructions blelow and running it. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/954421e5-9251-498d-a3c4-b2f9ef805351)
Create an ANDI snippet
a. On your computer, open Chrome.
b. Press Ctrl + Shift + j on your keyboard to open the Developer Tools.
c. Click on the Sources tab to open the Sources panel.
d. Click the Snippets tab to open the Snippets pane. You might need to click More Tabs in order to access the Snippets option.
e. Click New snippet to create a new snippet.
f. Right-click it and select Rename... to rename it.
g. Type ANDI and then press Enter.
h. Drag and drop the ANDI bookmarklet from the bookmarklet bar into the Code Editor pane.
i. Press Cntrl + Enter on your keyboard, to save the ANDI snippet and run it.
Any time you want to launch ANDI to evaluate a webpage
a. Press Ctrl + Shift + j on your keyboard to open the Developer Tools.
b. Click on the Sources tab to open the Sources panel.
c. Click the Snippets tab to open the Snippets pane. You might need to click More Tabs in order to access the Snippets option.
d. Right-click on ANDI snippet and select Run to launch ANDI.
e. When you want to launch ANDI again after moving to a new webpage, right-click on the ANDI snippet and select Run.
