### ISSUE TITLE
Full panel/Interactive example for Alt DA Non-Index/Major Portion

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#2671]
Please create a full panel/interactive example for Alternative Dual Accounting in a Non-index Zone from this page https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=major-portion-area and using this example:  https://onrr.gov/document/Revised.Reporting.Using.Alternative.Dual.Accounting.for.Processed.Gas.in.Non-Index.Zone.Major.Portion.Areas.pdf.  The statement is the same one as the one for Actual Dual Accounting a box above it.

If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

**Comment by cthomasONRR** [comment]
Images are already in the CMS, located here: https://dev-onrr-cms.app.cloud.gov/admin/files/folders/02b2b8d0-ca86-40f0-9c6b-4c50d6aed936

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Do you have time to review before I share with Jodie? https://dev-onrr-frontend.app.cloud.gov/references/valuation/rpmp-alt

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Looks great! Here are some things I found:

- Weird line break here:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/ae14940f-0bfc-401f-9a86-cd25721981e6)
- Another unneeded line break here:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/5ac97842-2c69-4b0f-a87f-f78c4c2779ed)
- I think this text is used all examples. Since the examples don't address the exact same product codes every time, I think we should remove the PC numbers and reword this sentence to say "This examples addresses reporting and calculations for various product codes." (This example also includes PC04 calculations.) I'm also open to other text options, that's just what I can come up with right now.
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/0f73d320-359b-4267-8e43-92da2276bb0a)

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Awesome, thank you! I used your text for the product codes and we can change it if we or RV wants us to

**Comment by eelzi-ONRR** [comment]
@jpetersononrr This is ready for review:

Th examples page that will link to it: 
https://dev-onrr-cms.app.cloud.gov/references/valuation/rpmp-alt

The interactive example: https://dev-onrr-frontend.app.cloud.gov/references/valuation/rpmp-alt

**Comment by jpetersononrr** [comment]
Thank you!

Sorry for the delay!

The big thing I see is that the actual "example" is included in the minimum value tab.  If that's a glitch in my cookies or something, let me know!  In the "actual DA" one for MP, it looks like we used a "calculations" tab for that section.  

Thanks!

**Comment by eelzi-ONRR** [comment]
@jpetersononrr The calculations tab has been added: https://dev-onrr-frontend.app.cloud.gov/references/valuation/rpmp-alt?tabs=detailed-example,minimum-value-requirement

**Comment by jpetersononrr** [comment]
Awesome!  Thank you!  Looks great!

**Comment by eelzi-ONRR** [comment]
Great! This is now live and linked to on the valuation examples page: 

https://onrr.gov/references/valuation/rpmp-alt?tabs=detailed-example,major-portion-value-requirement

https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=major-portion-area
