### ISSUE TITLE
Full Panel/Interactive Example for Revised Alt DA Unprocessed Gas

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#2673]
Please create a full panel/interactive example for Revised Reporting of Unprocessed Gas Alternative Dual Accounting in a Non-index Zone from this page https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=major-portion-area and using this example:  https://onrr.gov/document/Revised_Reporting_Using_Alternative_Dual_Accounting_for_Unprocessed_Gas_in_Non-Index_Zone_MP_Areas.pdf.  The statement is in the example.

If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

**Comment by cthomasONRR** [comment]
Images are already in the CMS, located here: https://dev-onrr-cms.app.cloud.gov/admin/files/folders/1efa35d3-04e2-40ae-bdf9-929331f0d5f7

**Comment by cthomasONRR** [comment]
@lpgoldstein 

- The PDF icon is missing here:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/87ac7f7b-f000-43ca-94cf-90734c53649d)
- Make sure all links have breadcrumb only- these should be linking to dev since we're in dev but they're bringing me to the live site. This applies to all links in this example. 
- Also, the PDF icon is missing from the map link... and the map link gives me a 404. The handbook link is also giving me a 404. They are using old website links throughout the example, so all of these links need to be updated.
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/074fd6e6-1d02-40e7-898c-f6f826eefca7)
- This Major Portion Prices URL is redirecting correctly, but it would be nice to have the latest link with no redirects (The URL is from the old site). I'm seeing this issue throughout the example.
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/24964ac0-c39c-4fd9-801d-155519dff866)
- Update all links in every tab... some are redirecting, some are giving me 404
- You're missing the product codes tab. You can reuse the product codes tab contents seen in other examples. I made sure the explanation text was generalized for all examples.

**Comment by lpgoldstein** [comment]
@cthomasONRR Thanks!

**Comment by lpgoldstein** [comment]
@jpetersononrr Ready for your review

**Comment by cthomasONRR** [comment]
@lpgoldstein 

PDF file is missing here:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/601134de-7cc8-4828-9592-b470cea3228d)

PDF icon missing here:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/1a58e51f-5485-4093-8403-55311ff3d3cb)


PDF icon missing here:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/758ed173-0043-4386-b1e6-7fbe3c73937a)

**Comment by jpetersononrr** [comment]
Do you have the url?  Sorry...that's on me for not being able to find it!

**Comment by lpgoldstein** [comment]
@jpetersononrr it's on me - I didn't put in here - https://dev-onrr-frontend.app.cloud.gov/references/valuation/rump-alt?tabs=overview

**Comment by jpetersononrr** [comment]
Thanks!

On the overview tab, the font for the "finally, this example" at the bottom seems weirdly large.  It doesn't need to be a header.
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/64428541/ef8d3a06-87cc-4d0a-a5fd-5577fd70d3cf)

The numbers are in the "minimum value" tab as well.  Can we add a final one called "calculations" and put the numbers in there? 

Thanks!!

**Comment by lpgoldstein** [comment]
@jpetersononrr I don't understand what you want to add. Do you want to add an additional tab called "calculations"? Can you send me a screenshot of what you want to be in that tab?

**Comment by jpetersononrr** [comment]
Sure!  The way it is in this example: https://onrr.gov/references/valuation/rpmp-act?tabs=detailed-example,major-portion-value-requirement

The last tab says "calculations" and has the "actual" example in it.  Yes there's a TON of caveats for someone to get through first!  We want to make sure people know what applies to the situation because it is so specific.  Thanks!

**Comment by lpgoldstein** [comment]
@jpetersononrr Got it - How does this look https://dev-onrr-frontend.app.cloud.gov/references/valuation/rump-alt?tabs=detailed-example,major-portion-value-requirement

**Comment by lpgoldstein** [comment]
@jpetersonnonrr This is live! Assumptions are open.
