### ISSUE TITLE
Full panel/interactive example for Non-Dedicated Alt DA

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#2674]
Please complete a full panel/interactive example for Non-dedicated Alternative Dual Accounting on this page:  https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=index-zone-arms-length-non-dedicated-contract using this example:  https://onrr.gov/document/Processed.Gas.ALNDC.Index.Alt.DA.pdf.  The sample statement is the same as for the major portion examples.

If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

**Comment by cthomasONRR** [comment]
Acronym: "PND-Alt" (Processed Gas, Non-Dedicated Contact, Alternative Dual Accounting)

Image file folder here: https://dev-onrr-cms.app.cloud.gov/admin/files/folders/49ca0741-f542-409f-8a8c-fefbefab866b

**Comment by jpetersononrr** [comment]
Here is the statement for this example.  Thanks!
[Indian Example processed gas plant statement (3).pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/12882651/Indian.Example.processed.gas.plant.statement.3.pdf)

**Comment by lpgoldstein** [comment]
https://dev-onrr-cms.app.cloud.gov/admin/files/b0843d92-ca4f-4ece-a03f-10eaec9103dd

**Comment by lpgoldstein** [comment]
@AlexandracmONRR @eelzi-ONRR Does one of you have time to review this example before I send to Jodie to review? 
https://dev-onrr-frontend.app.cloud.gov/references/valuation/pnd-alt?tabs=overview&panel=assumptions-indian-example-processed-gas-reporting-non-dedicated-contract-in-an-index-zone-using-alternative-dual-accounting

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - I will review this tomorrow morning!

**Comment by eelzi-ONRR** [comment]
@lpgoldstein Good work! I found a few things: 

**Overview**
- Since this is the only Download PDF link on the page, it's okay to use download PDF. That's what we've used on the other examples if we want to be consistent.
- The link to ONRR Reporter and Payor Handbooks is the link for the old site (it should probably also be changed in the PDF if Jodie can provide a new one)
-  Indian Gas Index Zone Prices web page - we can remove the word "web" since they are already on the website
-  The internal links should be done as slugs. I think most (all?) of these have the entire URL entered

**Detailed Example**
- Check internal links to be slugs, not full URLS
- First tab has a previous tab link
- Second Tab - the link should either have a PDF icon or go to the interactive example if we have one yet
- Third Tab - in step 4, since we can't highlight the line on the table, should we bold the text in that line?; I don't think this tab needs a Next Tab link - for other examples we've only used these next and previous tabs for the subtabs in the detailed example section since that part is linear

**Product Codes**
- This tab on other examples has a blurb above the image: This example addresses reporting and calculations for various product codes. You can find more information about product codes and reporting in the ONRR Reporter and Payor Handbooks.

**Comment by AlexandracmONRR** [comment]
Links (general): I think that almost all the links have the entire onrr.gov URL, but they should just have the slugs (as Erin noted yesterday). There are a couple that are correct.

Sample Statement: Bold the blue letters in the table.

Detailed example: 
2nd tab: this can link to the RV example that I'm working on currently... but it wont be ready until early next week "/references/valuation/pnd-act"

**Comment by lpgoldstein** [comment]
@eelzi-ONRR @AlexandracmONRR all changes made and have updated the link to Alex's pnd-act example.

**Comment by eelzi-ONRR** [comment]
@lpgoldstein 

The link in the 2nd tab for detailed example still goes to the PDF, not Alex's example. 
The link text on the Product codes tab needs to be fixed (it not currently a link, just highlighted)

Everything else looks good!

**Comment by lpgoldstein** [comment]
@jpetersononrr ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation/pnd-alt?tabs=overview

**Comment by lpgoldstein** [comment]
Published!
