### ISSUE TITLE
Full panel/interactive example for Non-dedicated Actual DA

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#2675]
Please complete a full panel/interactive example for Non-dedicated Actual Dual Accounting on this page:  https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=index-zone-arms-length-non-dedicated-contract using this example:  https://onrr.gov/document/Processed.Gas.ALNDC.Index.Actual.DA.pdf.  The sample statement is the same as for the major portion examples.

If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

**Comment by jpetersononrr** [comment]
Here is the statement for this example.  Thanks!
[Indian Example processed gas plant statement (3).pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/12882654/Indian.Example.processed.gas.plant.statement.3.pdf)

**Comment by AlexandracmONRR** [comment]
Linked is the sample statement already in the CMS with alternative text: 
https://dev-onrr-cms.app.cloud.gov/admin/files/b0843d92-ca4f-4ece-a03f-10eaec9103dd

**Comment by AlexandracmONRR** [comment]
Hi @lpgoldstein or @eelzi-ONRR - would you be able to review my RV example?

You can find it here: https://dev-onrr-frontend.app.cloud.gov/references/valuation/pnd-act

**Comment by lpgoldstein** [comment]
@AlexandracmONRR I can take a look.

**Comment by lpgoldstein** [comment]
@AlexandracmONRR looks great! Just a few things. 

1. The assumptions need to be formatted as a list because it's not recognized as a list by ANDI. The min ngl example has one and Erin is working on one as well. 
2. This should be a link - I know it isn't in the PDF either though. 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/9603b9a6-caba-48db-b44f-db889eef27eb)
3. Step 4 of PC03 is missing the image
4. This should be a link as well in PC 07 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/be097d47-a3f5-462e-ba3e-d10fe5561085)
5. In PC07 step 1a Copy and paste in as plain text to fix the text shade 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/2a17947e-1da1-4f7b-8e6b-ed3dc674b824)
6. Same with next table. 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/b3265bcf-d3fa-4762-ba61-cd47b4759bce)
7. Step 1c table 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/1ea7bba0-dd55-4649-8e5f-f6d1e7257731)
8. This text looks too light and might need the paste as plain text trick to fix it. I could be wrong though too. 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/3bab49c3-4714-458b-a83a-d09b2aea5d34)
9. Step 2a table text 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/12b0bcab-f8ed-46fa-9610-71f461f299f8)
10. Does this need a pdf icon? 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/fb68fc29-6f53-43c9-804d-28f4f42680d3)
11. This text looks too like as well - PC15
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/b6a6f8b9-a1a8-4c00-aae5-5752f64ad38f)

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - thanks for your review. I've taken care of the issues. The only thing I have a question on is: in the assumptions panel, I made it into a list, but because it was a list I couldn't insert a table below Step 11, so I added a parenthesis that states that the table is located after the list. is that okay?

https://dev-onrr-frontend.app.cloud.gov/references/valuation/pnd-act?tabs=detailed-example,pc15

**Comment by lpgoldstein** [comment]
@AlexandracmONRR Yep! It reads a list now in ANDI and the table is still really close to the step. Erin and I just discussed yesterday.

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - would you be able to do one final review before I send this to Jodie?

https://dev-onrr-frontend.app.cloud.gov/references/valuation/pnd-act

**Comment by lpgoldstein** [comment]
@AlexandracmONRR I think you got them all. This was another tough one!

**Comment by AlexandracmONRR** [comment]
@jpetersononrr - this is ready for your review! Please let me know if you have any edits; if you do not, I will publish live.

Thank you!

**Comment by jpetersononrr** [comment]
This looks great!  Thank you!

**Comment by AlexandracmONRR** [comment]
@jpetersononrr - thanks for your review!

The page is now live here: https://onrr.gov/references/valuation/pnd-act
