### ISSUE TITLE
Full panel/interactive example for Dedicated Alternative DA

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#2677]
Please complete a full panel/interactive example for Dedicated Alternative DA on this page:  https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=index-zone-arms-length-dedicated-contract using this example:  https://onrr.gov/document/Processed.Gas.ALDC.Index.Alt.DA.pdf.  The statement is the same as the major portion examples.

If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

**Comment by cthomasONRR** [comment]
@AlexandracmONRR 

- Please bold the correct words and add periods to the end of sentences:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/f6f3eda9-c538-4172-adc9-45d19d7a973c)
- This information goes in the Sample Statement tab (which is not preset). You are missing the sample statement image. If it wasn't provided, please follow up with Jodie.![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/8cfb3071-e0ae-41f1-98fc-1c5cbb482561)
- In Assumptions, they should be numbered not bullets. I'm pretty sure the purple card show be under Assumption 7. 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/50b1c618-a38e-4981-a016-1251ca4d61a8)
- This information should be in the overview tab 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/a9fef043-64b4-49bb-87ff-1223c56f7eb7)
- I believe this should also be in the overview tab. Link to pricing page is also needed 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/72e3dc7a-8c0f-4e50-8a7c-7c8154bacf0a)
- I think this should be its own subtab within the detailed example. Also remember to bold appropriate words
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/06d140f5-e19f-41a6-9cdc-276cfc995e76)
- This note needs to be moved to PC 03, before Step 1 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/b1990274-f2b7-4f1b-a9b8-235c7e335b59)
- These are both heading 3... not sure they should be same heading level. Please check heading levels throughout.
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/f0c9a817-e147-485e-ad1c-13f19775c775)
- Subbullets are needed. It's wonky in the CMS but see the following example for how to do it: (https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example?tabs=detailed-example,pc-03) 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/b5208f59-b5ba-40f9-bd4a-1f9dd0af6c54)
- This "B" should not be blue... it's part of the CFR cite 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/f5b66e3f-68b9-4970-9688-79aba921b09e)
- PDF icon missing here 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/296ae1fa-7a5b-4fce-ab09-8bb3448c5b3d)
- This line is wrong- check PDF for correct wording 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/a786e8e9-f5ee-4102-9879-7a76b868f77b)
- Heading is wrong here. Step A should have strikeout, but don't think we're able to do that in the CMS. Step B doesn't need italics either. 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/bbaa7136-2f62-4c0b-becd-2496d805039d)
- I think the content and the tabs are switched: 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/339a759c-3030-40ba-a0dd-d6df073d83dc)
- I'm honesty really confused in the Parts B and C subtabs... please check that work because I'm having trouble matching with the PDF.

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - here is the drafted alt text for this sample statement:
[Indian Example processed gas plant statement.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnVKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3dcd040b90f9838b1d774451e616eae20d5e294a/Indian%20Example%20processed%20gas%20plant%20statement.pdf)

Sample Indian Processed Gas Example Statement for Initial Reporting for processed gas in index zone with alternative dual accounting. These sections are indicated with bolded, blue letters. The Wellhead Information section contains letters A, B, D, E, and O.  "A" indicates the location of Gross Wellhead MCF or 2,458.00. "B" indicates the Gross Wellhead MMBTU or 3,013.00. "D" indicates the Contractual Field Deducts for MCF or -129.75 and MMBTU or -162.20. "O" indicates the Net Delivered MMBTU or 2,850.80. The Component Settlement section contains the letters S, P, R, L, Q, M, and N. "S" indicates the column for Allocated and "L" indicates the Subtotal for liquids of 6,903.59. "P" indicates the column for Contract % and "R" indicates the Price. "Q" indicates the value of Shrink Subtotal Liquids or 602.01. "M" indicates Settlement Subtotal Liquids or 5,868.05. "N" indicates the Value Subtotal Liquids $4,998.51. The Residue Settlement section contains the letters E, F, G, H, I, J, and K. "E" indicates the Allocated Residue or 2,248.79. "F" indicates the Contractual Allocated Fuel or 326.40. "G" indicates the Net Residue MCF or 1,697.81. "H" indicates the Net Residue MMBTU or 1,922.39. "I" indicates the Contract % or 85.00. "J" indicates the Price 3.1390500. "K" indicates the Residue Value or $5,129.31.

**Comment by Maroyafaied** [comment]
@AlexandracmONRR attached are my changes, I looked at the pdf which had a description for most of the letters and also it looks like we have [alt text in the CMS for a very similar plant statement ](https://dev-onrr-cms.app.cloud.gov/admin/files/5599773c-0480-48cb-8235-562a8cb466c4)so I tried to be consistent.  [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnFLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dbbba641208d49a96e40ef1af8a61a58166abf51/image.png)

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - please see the edited [PD-Alt RV example](https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-alt). Many thanks to Christine for her review.

**Comment by Maroyafaied** [comment]
@AlexandracmONRR Below is a list of corrections, please tag me or Christine to do a final review after you've made the changes. Thanks!

**Overview Tab**
- This link is incorrect, it doesn't go to the handbook
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/a787374c-c36b-4c05-9a4d-6b63b5479e63)
- add link to the Indian Gas Index Zone price webpage 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/8874ac05-785a-4941-9d7c-8f6f96237b4f)

**Detailed Example Tab**
- Take out "P" in step 15 within the assumption box
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/1643db43-5757-493b-8949-ec7e39215069)

**Part A: PC 03 Tab**
- Capitalize the "P" in Proceeds
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/b7f1522b-e347-4145-b213-0e9b6b2e3b74)
- Make "(F)" in bold blue
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/637b3acf-a2bd-418c-94f2-290bd5cbf96a)

**Part A: PC 07 Tab**
- Title of this table is missing, it should say in bold "PC 07 Value of Regulatory Minimum Price Components (Step 2a):"
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/e485d8e3-8eb8-455b-a6e2-1d6fd352570a)

**Part A: PC 15 Tab:**
- This font seems to be lighter in color than the rest
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/b925995c-13ef-4159-aacb-b819b8040fbb)
- This bullet point is duplicated, it should say "The RVPA is $91.65"
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/9b9f2b45-77d0-48bd-8d87-c41c7c6b6ca7)

**Part A: RVLA**
- Capitalize the P in "Proceeds"
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/5c191a07-8cba-4273-8baa-a6042bfc5926)
- This link goes to a dev link that doesn't work, please add the correct link 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/e5ee85ca-9212-4862-957d-83d2fbe2986f)
- Put this part in italic 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/b011122a-14bb-47a3-acc1-4baf1708f14e)

**In all tabs**
- The  "Next Tab" and "Previous Tab" link is missing in the bottom of each tab, see this example
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/945a2dfa-7881-48cf-a50f-606eac44bccf)

**Comment by AlexandracmONRR** [comment]
@Maroyafaied and @cthomasONRR - thanks for all your review. I've finished up the 2nd round of edits. Please let me know if this is ready for sending for SME review.

[Example](https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-alt)

**Comment by Maroyafaied** [comment]
@AlexandracmONRR Everything looks good, I checked on the my edits and Christine's and I believe you updated it all. The only thing I didn't review is the heading levels,  @eelzi-ONRR or @cthomasONRR would be better and quicker than me to check heading levels, I'd appreciate it if one of you could review just the levels. @AlexandracmONRR after the heading level review, please go ahead and send the example to Jodie. Thanks

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR 

- The Sample Statement Tab needs a heading

- On the detailed example tabs, the substeps should be level 5. 

For example, Step 2 is an H4, so Step 2a and Step 2b should be H5. And in this instance the table headings will need to be an H6 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczZaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ead4362ec8203edb4cfdf6ccdce10b99d474ea8f/image.png)

@Maroyafaied Maybe next week at sync-up I can demo how to use ANDI to check headings? For headings I find it easier and more accurate than other tools

**Comment by AlexandracmONRR** [comment]
@jpetersononrr - hi, please review the interactive example for the [Dedicated Alternative DA](https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-alt). 

If you have any edits, please add them to this issue. If you do not have any edits, please send your approval.

**Comment by jpetersononrr** [comment]
First:  I LOVE the tab labels!!  Thank you for including the A, B, and C!

This one looks great too!  Could we expand the assumptions box on this one as well?  I mentioned it in a previous one, but having it expanded to start puts the ownership on the reader to read it or ignore it but they can't say we hid it!  Thanks!

**Comment by jpetersononrr** [comment]
That looks great!  Thank you!

**Comment by AlexandracmONRR** [comment]
The PD-Alt interactive example is now live: https://onrr.gov/references/valuation/pd-alt
