### ISSUE TITLE
Add tips for using interactive handbooks

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2748]
As per user study 15, some handbook users avoid using the interactive handbooks because they aren't sure how they work. We recommend adding some tips to help users understand how to use them. We also can explain to users what to do if they encounter the problem in issue #2608

https://onrr.gov/references/handbooks

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @Maroyafaied 

I'm planning to add this text to a yellow card that will be located above the tabs in each interactive handbook webpage. 

I added it to one in dev for you to review: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook

This text is as follows:

This interactive handbook breaks down the full handbook PDF so specific topics are more easily found.

- The table of contents tab provides links to each section of the handbook.
- The chapters tab contains PDFs of individual chapters.
- The supplemental information tab contains PDFs of individual appendices and supplemental reporting guidance.

Please note: When users have Adobe's web browser extension activated, the links within the table of contents tab all open to page one instead of the specified page. The Adobe extension needs to be deactivated in order for the table of contents hyperlinks to operate correctly.

- [Learn how to disable an extension in Chrome](https://support.google.com/chromebook/answer/2589434?hl=en)
- [Learn how to disable an extension in Microsoft Edge](https://support.microsoft.com/en-us/microsoft-edge/add-turn-off-or-remove-extensions-in-microsoft-edge-9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026#:~:text=In%20Microsoft%20Edge%2C%20select%20Extensions%20located%20to%20the%20right%20of,you%20want%20to%20turn%20off)

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks! I incorporated your edits here: 
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=table-of-contents

**Comment by Maroyafaied** [comment]
Looks good!

**Comment by eelzi-ONRR** [comment]
@cthomasONRR This is great! I have some very minor suggestions. 
@Maroyafaied one of my suggestions changes your suggestions

**Change:** 
This interactive handbook breaks down the complete handbook PDF so specific topics are more easily found.
**To This:** 
This interactive handbook breaks down the complete handbook PDF so specific topics are more easy to find.  


**Change:**
See note below for best use.

This language in it's current position violates 508. But if you reorder the bullet points to put the table of contents tab bullet point last, then you can keep the note since it refers to what is directly below it.  Or maybe you don't need the message to see below?

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Thanks for bringing that to my attention, I think it's ok to remove the "see below" message.

**Comment by cthomasONRR** [comment]
@eelzi-ONRR and @Maroyafaied I made Erin's changes and removed the "see below".
Please do one more final review, then I'll add this card to all interactive handbook pages, and then go live. Thanks!

**Comment by eelzi-ONRR** [comment]
Looks good!

**Comment by cthomasONRR** [comment]
Ok, this is live on all the interactive handbooks! I changed the card color to purple. I also did not include it in the Indian Payor Handbook because the tips do not apply to this handbook (which is set up more like an RV interactive example)
