### ISSUE TITLE
Review expansion panels with 1 card and change to content block if possible

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2808]
Example: https://onrr.gov/about/contact/lease-agreement-contacts?panel=i-need-contract-or-lease-expiration%2Ftermination-information

This sheet might be helpful in looking for pages that have cards on expansion panels: [link](https://doimspp-my.sharepoint.com/:x:/g/personal/elzie_mms_gov/ESba5npiehFEmhNcpwF6-qYB5Bh3Nq7aEyHnlX5x_IcFrg?e=o4U3Uq)

**Comment by eelzi-ONRR** [comment]
Also consider putting both the customer ID contacts as a single content block instead of two cards. Especially since users have to email both people. https://onrr.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id

**Comment by AlexandracmONRR** [comment]
**Changes**:

- I need an FMP, gas plant... (found in: Oil & Gas Production - Reporting and Contacts sections)
_This required some review of the cards currently used. We changed some of the text in this accordion, and then reused the card called "Reference List - 2014"_

- I need to file a CMP-2014 (found in: Oil & Gas Revenue - Reporting)
_Switch to a content block from Indian References, removing the use of a card._

- I have a question about solid minerals valuation (found in: Solid Minerals - Reporting)
_Make card into a content block, use presentations listed in New Reporter Training section._

- I have a question about solid mineral compliance or enforcement ((found in: Solid Minerals - Reporting)
_Make into a content block, and use presentations listed in New Reporter Training section._

- I need a contract or lease expiration/termination information (found in: Lease & Agreements - Contacts)
_Change "Check MLRS" card to content block and fix text._

- I need to update the lessee of record (found in: Lease & Agreements - Contacts)
_Change to content block._

- I have other questions about a lease (found in: Lease & Agreements - Contacts)
_Change "Check MLRS" card to content block and fix text._

**Comment by AlexandracmONRR** [comment]
**What to keep the same:**

- I need to troubleshoot errors in my 2014 (found in: Oil & Gas Revenue - Reporting; Geothermal - Reporting and Contacts; Oil & Gas Royalty - Contacts)
_Do not change, because these cards are sometimes updated, and it could create easily outdated links if any troubleshooting item is not changed._

- I need to adjust a previously filed 2014 (found in: Oil & Gas Revenue - Reporting; Geothermal - Reporting and Contacts; Oil & Gas Royalty - Contacts)
_Do not change, because these cards are sometimes updated, and it could create easily outdated links if any troubleshooting item is not changed._

- I need help understanding the Indian Oil Rule (found in: Oil & Gas Royalty - Contacts)
_Do not change, because list of videos is sometimes updated._

- I need to resent my password (found in: Oil & Gas Rent - Contacts)
_Do not change, because this card is used across the site and has been standardized._

- I need help using Online Rental … (ORPS) (found in: Oil & Gas Rent - Contacts)
???
