### ISSUE TITLE
Event Calendar for November

### ISSUE THREAD

**Issue by Toddsand21** [DOI-ONRR/onrr.gov-site#2890]
Please see the attached file.

[FY 2024 ALL EVENT CAL_NOV_2023.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/13230265/FY.2024.ALL.EVENT.CAL_NOV_2023.docx)

Please let me know if you have questions, and please save the October Events calendar posting and send me a copy of them for my records before you delete them.

**Comment by cthomasONRR** [comment]
@Toddsand21 

The November events are ready for your review in dev: 
https://dev-onrr-frontend.app.cloud.gov/events?tabs=indian-outreach-events

Our CMS is not meant for archival storage. Since my team is not the content owner, it is the SME's responsibility to retain their own records. Because this information is on the live site, I think the best method would be for your to either copy+paste the old events in a document or do screen captures.

**Comment by Toddsand21** [comment]
It looks fine and ready.

**Comment by cthomasONRR** [comment]
@Toddsand21 

Great, these are now live: https://www.onrr.gov/events?tabs=indian-outreach-events

Thanks for your time and help,
Christine
