### ISSUE TITLE
Meet about sitemap review 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2895]
@AlexandracmONRR please schedule a meeting before @cthomasONRR starts her review to discuss changes and things we made exceptions for.

**Comment by AlexandracmONRR** [comment]
I set up a meeting for Wednesday 11/8.

**Comment by AlexandracmONRR** [comment]
- **File Collection**: File collection can be used for CMS collections, file download lists, or video lists or cards/titles with documents listed (since we are not mapping out each individual document). Cards with file downloads and video collections should include the number of file downloads or videos linked. Use the orange stacked boxes.
- **Contact Categories/Cards**: two types of contact cards - a singular category card for a specific contact (simple yellow box) and a multiple category contact card for several contacts that includes number of contacts (stacked yellow box).
- **External Links**: do NOT use the numbering hierarchy throughout the site map; but include a part of the URL underneath the title of the external link.
- **Internal Links**: do NOT use the numbering hierarchy, but dynamically link to the correct page
- **Introductory text links**: Sections that have links that show up in the introductory text but without a subtitle, should be inserted at the top by adding a "0" to the end.
- **Note pages that are exceptions**: note pages that have exceptions to the format; this is often due to the complexity of the pages.
- For example: 3.8.5, 3.8.5.1, 3.8.5.2 are all extremely complex pages that have been formatted as more high level.
